BookReviewsProject/urls.py
from django.contrib import admin
from django.urls import path, include
import reviews.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('books/', include('books.urls')),
    path('reviews', reviews.views.show_reviews, name="view_reviews_route"),
    path('reviews/create/<book_id>', reviews.views.create_review, name="create_review_route")
]

books/urls.py
from django.contrib import admin
from django.urls import path, include
import books.views

urlpatterns = [
    path('', books.views.index, name="show_book_route"),
    path('create', books.views.create_book),
    path('update/<book_id>', books.views.update_book, name = 'update_book_route'),
    path('delete/<book_id>', books.views.delete_book, name = 'delete_book_route'),
    path('view/<book_id>', books.views.view_book_details, name = 'view_book_details')
]

books/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Genre(models.Model):
    title = models.CharField(blank=False, max_length=255)

    def __str__(self):
        return self.title


class Tag(models.Model):
    title = models.CharField(blank=False, max_length=255)

    def __str__(self):
        return self.title


class Book(models.Model):
    title = models.CharField(blank=False, max_length=255)
    ISBN = models.CharField(blank=False, max_length=255)
    desc = models.TextField(blank=False)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)


    def __str__(self):
        return self.title

reviews/models.py
from django.db import models
from django.contrib.auth.models import User
import books.models


# Create your models here.
class Review(models.Model):
    book = models.ForeignKey(books.models.Book, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, blank=False)
    content = models.TextField(blank=False)
    date = models.DateField(blank=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title + " for " + self.book.title

books/forms.py
from django import forms
from .models import Book, Genre


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'desc', 'ISBN', 'genre', 'tags', 'owner', 'photo')


class SearchForm(forms.Form):
    title = forms.CharField(max_length=100, required=False)
    genre = forms.ModelChoiceField(queryset=Genre.objects.all(), required=False)

reviews/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('title', 'content', 'date')
    

books/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.db.models import Q
from .models import Book, Genre
from .forms import BookForm, SearchForm
from reviews.forms import ReviewForm


# Create your views here.
def index(request):
    books = Book.objects.all()

    # if there is any search queries submitted
    if request.GET:
        # always true query:
        queries = ~Q(pk__in=[])

        # if a title is specified, add it to the query
        if 'title' in request.GET and request.GET['title']:
            title = request.GET['title']
            queries = queries & Q(title__icontains=title)

        # if a genre is specified, add it to the query
        if 'genre' in request.GET and request.GET['genre']:
            print("adding genre")
            genre = request.GET['genre']
            queries = queries & Q(genre__in=genre)

        # update the existing book found
        books = books.filter(queries)

    genres = Genre.objects.all()
    search_form = SearchForm(request.GET)
    print(books.query)
    return render(request, 'books/index.template.html', {
        'books': books,
        'genre': genres,
        'search_form': search_form
    })


def view_book_details(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    review_form = ReviewForm()
    return render(request, 'books/details.template.html', {
        'book': book,
        'form': review_form
    })


def create_book(request):
    if request.method == 'POST':
        create_form = BookForm(request.POST)

        # check if the form has valid values
        if create_form.is_valid():
            book = create_form.save()
            messages.success(request, f"New book {book.title} has been created")
            return redirect(reverse(index))
        else:
            # if does not have valid values, re-render the form
            return render(request, 'books/create.template.html', {
                'form': create_form
            })
    else:
        create_form = BookForm()
        return render(request, 'books/create.template.html', {
            'form': create_form
        })


def update_book(request, book_id):
    # 1. retrieve the book that we are editing
    book_being_updated = get_object_or_404(Book, pk=book_id)

    # 2. if the update form is submitted
    if request.method == "POST":

        # 3. create the form and fill in the user's data. Also specify that
        # this is to update an existing model (the instance argument)
        book_form = BookForm(request.POST, instance=book_being_updated)
        if book_form.is_valid():
            book_form.save()
            return redirect(reverse(index))
        else:
            return render(request, 'books/update.template.html', {
                "form": book_form
            })
    else:
        # 4. create a form with the book details filled in
        book_form = BookForm(instance=book_being_updated)
        return render(request, 'books/update.template.html', {
            "form": book_form
        })


def delete_book(request, book_id):
    book_to_delete = get_object_or_404(Book, pk=book_id)
    if request.method == 'POST':
        book_to_delete.delete()
        return redirect(index)
    else:
        return render(request, 'books/delete_book.template.html', {
            "book": book_to_delete
        })

reviews/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from .forms import ReviewForm
from .models import Review
from books.models import Book


def show_reviews(request):
    reviews = Review.objects.all()
    return render(request, 'reviews/show_reviews.template.html', {
        'reviews': reviews
    })


def create_review(request, book_id):
    if request.method == "POST":
        form = ReviewForm(request.POST)
        # create an instance of review, but don't commit, so that we have a chance to set the user
        review = form.save(commit=False)
        review.user = request.user
        review.book = get_object_or_404(Book, pk=book_id)
        review.save()
        messages.success(request, "New review has been added - " + review.title)
        return redirect(reverse('view_reviews_route'))
    else:
        form = ReviewForm()

    return render(request, 'reviews/create_review.template.html', {
        'form': form
    })

books/templates/books/create.template.html
{%extends 'base.template.html' %}
{%load crispy_forms_tags %}

{%block content%}
    <form method="POST">
    {% csrf_token %}
    {{ form|crispy}}
    <input type="Submit"/>
    </form>
{%endblock%}

books/templates/books/delete_book.template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Delete book {{book.title}}</h1>
    <p>Are you sure?</p>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes"/>
        <a href="{% url 'show_book_route' %}">No</a>
    </form>
</body>
</html>

books/templates/books/details.template.html
{% extends 'base.template.html' %}

{% block content %}
<h1>{{book.title}}</h1>
<p>
    ISBN: {{book.ISBN}}
</p>
<p>
    Author: {{book.author.first_name}} {{book.author_last_name}}
</p>
<p>
    Genre: {{book.genre.title}}
</p>
<p>
    Tags: {% for t in book.tags.all %} <span class="label">{{t.title}}</span> {%endfor%}
</p>
{{book.reviews}}
{%for r in book.review_set.all %}
<div class="card">
    <h3>{{r.title}}</h3>
    {{r.content}}
</div>

<form method="POST" action="{% url 'create_review_route' book_id=book.id %}">
{% csrf_token %}
{{ form|crispy}}
<input type="submit"/>
</form>

{%endfor%}
{% endblock %}

books/templates/books/index.template.html
{% extends 'base.template.html' %}
{%load static %}
{% load crispy_forms_tags %}

{%block content%}
    <h1>Books</h1>
    <form method="GET">
    {{search_form|crispy}}
    <input type="submit" value="Search"/>
    </form>
    <p>
        Here you can see all the books that we have.
    </p>
    <ul>
        {%for book in books %}
        <li>
            <a href="{% url 'view_book_details' book_id=book.id %}">{{book.title}}</a> 
            <a href="{% url 'update_book_route' book_id=book.id %}">Edit</a>
            <a href="{% url 'delete_book_route' book_id=book.id %}">Delete</a>
        </li>
        {%endfor%}
    </ul>
{%endblock%}

books/templates/books/update.template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit"/>
    </form>
</body>
</html>

reviews/templates/reviews/create_review.template.html
{% extends 'base.template.html' %}
{% load crispy_forms_tags %}

{%block content%}
<form method="POST">
    {% csrf_token %}
    {% include 'reviews/reviews_form.template.html' %}
    <input type="submit">
</form>
{%endblock%}

reviews/templates/reviews/review_form.template.html
{% load crispy_forms_tags %}
{{ form|crispy}}

reviews/templates/reviews/show_reviews.template.html
{%extends 'base.template.html' %}

{%block content %}
<ul>
    {%for r in reviews%}
    <li>{{r.title}}</li>
    {%endfor%}
</ul>
{%endblock%}

templates/base.template.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>{%block title%}{%endblock%}</title>
  </head>
  <body>
    <div class="container">
        {% if messages %}
        <div class="alert alert-success">
            
            <div>
                {% for message in messages %} {{ message }} {% endfor %}
            </div>
        </div>
        {% endif %}


    {%block content%}{%endblock%}
    </div>

    {%block js %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {%endblock%}
  </body>
</html>